name: Main Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [ "${{ github.head_ref }}" != "development" ]; then
            echo "Merges to main are only allowed from development branch"
            echo "⚠️ Current branch: ${{ github.head_ref }} ⚠️"
            exit 1
          else
            echo "✅ Branch check passed: merging from development to main"
          fi
